
//#define DONT_USE_GENERATE_CODE                                                                 
//------------------------------------------------------------------------------                 
// <auto-generated>                                                                              
//     This code was generated by Lockstep.CodeGenerator                                         
//                                                                                               
//     Changes to this file may cause incorrect behavior and will be lost if                     
//     the code is regenerated.                                                                  
//     https://github.com/JiepengTan/LockstepPlatform                                            
// </auto-generated>                                                                             
//------------------------------------------------------------------------------                 
                                                                                                 
using Lockstep.Serialization;                                                                    
namespace NetMsg.Common{                                                                            
#if !DONT_USE_GENERATE_CODE                                                                      

    [System.Serializable]                                                                           
    public partial class AccountData{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(Email);
			writer.Write(IsAdmin);
			writer.Write(IsEmailConfirmed);
			writer.Write(IsGuest);
			writer.Write(Password);
			writer.Write(Token);
			writer.Write(UserId);
			writer.Write(Username);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			Email = reader.ReadString();
			IsAdmin = reader.ReadBoolean();
			IsEmailConfirmed = reader.ReadBoolean();
			IsGuest = reader.ReadBoolean();
			Password = reader.ReadString();
			Token = reader.ReadString();
			UserId = reader.ReadInt64();
			Username = reader.ReadString();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class GameData{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(_UserId);
			writer.Write(_Username);
			writer.Write(_Datas);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			_UserId = reader.ReadInt64();
			_Username = reader.ReadString();
			_Datas = reader.ReadList(this._Datas);                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class GameProperty{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(_Name);
			writer.Write(_Type);
			writer.Write(_Data);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			_Name = reader.ReadString();
			_Type = reader.ReadInt16();
			_Data = reader.ReadArray(this._Data);                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class IPEndInfo{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(Ip);
			writer.Write(Port);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			Ip = reader.ReadString();
			Port = reader.ReadUInt16();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_C2G_LoadingProgress{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(Progress);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			Progress = reader.ReadByte();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_C2L_JoinRoom{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(RoomId);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			RoomId = reader.ReadInt32();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_CreateAccount{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(account);
			writer.Write(password);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			account = reader.ReadString();
			password = reader.ReadString();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_D2S_RepGameData{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(data);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			data = reader.ReadRef(ref this.data);                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_D2S_SaveGameData{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(result);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			result = reader.ReadByte();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_G2C_AllFinishedLoaded{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(Level);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			Level = reader.ReadInt16();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_G2C_GameStartInfo{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(LocalId);
			writer.Write(MapId);
			writer.Write(RoomId);
			writer.Write(Seed);
			writer.Write(SimulationSpeed);
			writer.Write(UserCount);
			writer.Write(TcpEnd);
			writer.Write(UdpEnd);
			writer.Write(UserInfos);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			LocalId = reader.ReadByte();
			MapId = reader.ReadInt32();
			RoomId = reader.ReadInt32();
			Seed = reader.ReadInt32();
			SimulationSpeed = reader.ReadInt32();
			UserCount = reader.ReadByte();
			TcpEnd = reader.ReadRef(ref this.TcpEnd);
			UdpEnd = reader.ReadRef(ref this.UdpEnd);
			UserInfos = reader.ReadArray(this.UserInfos);                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_G2C_Hello{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(GameId);
			writer.Write(LocalId);
			writer.Write(MapId);
			writer.Write(Seed);
			writer.Write(UserCount);
			writer.Write(UdpEnd);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			GameId = reader.ReadInt32();
			LocalId = reader.ReadByte();
			MapId = reader.ReadInt32();
			Seed = reader.ReadInt32();
			UserCount = reader.ReadByte();
			UdpEnd = reader.ReadRef(ref this.UdpEnd);                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_G2C_LoadingProgress{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(Progress);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			Progress = reader.ReadArray(this.Progress);                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_HashCode{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(StartTick);
			writer.Write(HashCodes);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			StartTick = reader.ReadInt32();
			HashCodes = reader.ReadArray(this.HashCodes);                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_RepAccountData{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(accountData);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			accountData = reader.ReadRef(ref this.accountData);                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_RepCreateResult{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(result);
			writer.Write(userId);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			result = reader.ReadByte();
			userId = reader.ReadInt64();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_ReqAccountData{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(account);
			writer.Write(password);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			account = reader.ReadString();
			password = reader.ReadString();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_S2D_ReqGameData{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(account);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			account = reader.ReadString();                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class Msg_S2D_SaveGameData{                                                                  
       public override void Serialize(Serializer writer){                                           
			writer.Write(data);                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
			data = reader.ReadRef(ref this.data);                                                                                     
       }                                                                                            
    }                                                                                              
                                                                              
#endif                                                                                           
}                                                                                               